### ISSUE TITLE
Publish package on PyPI

### ISSUE THREAD

**Issue by ecederstrand** [Edinburgh-Genome-Foundry/bioprinter#1]
Hi!

The install instructions in the README says to install via pip, but that doesn't work because the package does not exist on PyPI. I had to git clone and then run `pip install -e .` within the cloned repo.

Could you upload a package to PyPI, so `pip install bioprinter` works from anywhere? Thanks!

**Comment by Zulko** [comment]
Fixed. Thanks for the report!
