### ISSUE TITLE
Cannot install via pip

### ISSUE THREAD

**Issue by ecederstrand** [Edinburgh-Genome-Foundry/bioprinter#2]
I cannot install the package just uploaded to PyPI into a fresh virtualenv because it depends on `ez_setup` which is not installed:

```bash
$ python3.5 -m venv test_env
$ source test_env/bin/activate
(test_env) $ pip install bioprinter
Looking in indexes: https://pypi.org/simple
Collecting bioprinter
  Downloading https://pypi.org/packages/d9/3d/a823c9ad7b67b1b27029c1784afb2bf72a7d48827912fc0ac78f4c634fc8/bioprinter-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8rxmp23n/bioprinter/setup.py", line 1, in <module>
        import ez_setup
    ImportError: No module named 'ez_setup'
```

I can see that there's a local `ez_setup.py` in the repo, but either it's not being picked up by the import statement, or it is not mentinoned in the manifest file and has therefore not been bundled with the package on PyPI.

**Comment by Zulko** [comment]
Sorry for that, the issue was that ez_setup.py was left out of the MANIFEST file. This is fixed now. Could you try again and tell me if it worked ?

**Comment by ecederstrand** [comment]
Works now. Thanks!

**Comment by Zulko** [comment]
Happy bioprinting!

**Comment by ecederstrand** [comment]
Thanks!
